

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    RUN_REGION: us-east1
    SERVICE_NAME: "beam-processing-pipeline"
    WORKER_REGION: us-east1
    WORKER_MACHINE_TYPE: e2-medium
    NUM_WORKERS: 1
    MAX_WORKERS: 2
    TEMP_LOCATION: gs://dataflow_job_metadata/temp_location
    STAGING_LOCATION: gs://dataflow_job_metadata/staging_location

name: Build and Deploy to Dataflow
on:
  push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: checkout
        uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Test with pytest
        run: |
          pytest
  build-docker-image:
    name: build-docker
    needs: test
    environment: run_environment
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: |
          gcloud auth configure-docker us-docker.pkg.dev
      # Build the Docker image
      - name: Build
        run: |
          docker build -t us-docker.pkg.dev/$PROJECT_ID/docker-images/beam-processing-pipeline-github:latest -f Dockerfile .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |
          docker push us-docker.pkg.dev/$PROJECT_ID/docker-images/beam-processing-pipeline-github:latest
            # Push the Docker image to Google Container Registry
      - name: Build Flex Template
        run: |
          gcloud dataflow flex-template build gs://dataflow_job_metadata/templates/run_template_github.json --image us-docker.pkg.dev/$PROJECT_ID/docker-images/beam-processing-pipeline-github:latest --sdk-language PYTHON
      - name: Run Flex Template
        run: |
          gcloud dataflow flex-template run "data-processing-job-$(date +%Y-%m-%d)" \
            --template-file-gcs-location=gs://dataflow_job_metadata/templates/run_template_github.json \
            --worker-region=$WORKER_REGION \
            --worker-machine-type=$WORKER_MACHINE_TYPE \
            --region=$RUN_REGION \
            --service-account-email=${{ secrets.SA_EMAIL }} \
            --num-workers=$NUM_WORKERS \
            --max-workers=$MAX_WORKERS \
            --parameters gcp_project_id=$PROJECT_ID \
            --parameters temp_location=$TEMP_LOCATION \
            --parameters staging_location=$STAGING_LOCATION